import { useLocale } from 'next-intl';

// AI4Trade Signals PWA 的入口卡片。
// 只有配置了环境变量 NEXT_PUBLIC_PWA_URL(你部署好的 PWA 网址)时才显示,
// 否则渲染 null —— 网站外观零变化。文案内置 5 语言,不依赖 messages 文件。
const PWA_URL = process.env.NEXT_PUBLIC_PWA_URL;

type Copy = { title: string; desc: string; cta: string; risk: string };
const COPY: Record<string, Copy> = {
  zh: {
    title: 'AI4Trade Signals · 手机版',
    desc: '每个交易日前，机器人替你挑几只值得关注的票，并按你的本金算好仓位。首个交易日免费。',
    cta: '打开 App',
    risk: '信号由模拟机器人生成，仅供参考，不构成投资建议，交易风险自负。',
  },
  'zh-TW': {
    title: 'AI4Trade Signals · 手機版',
    desc: '每個交易日前，機器人替你挑幾檔值得關注的股票，並依你的本金算好倉位。首個交易日免費。',
    cta: '開啟 App',
    risk: '訊號由模擬機器人生成，僅供參考，不構成投資建議，交易風險自負。',
  },
  en: {
    title: 'AI4Trade Signals · Mobile',
    desc: 'Before each trading day, the bot picks a few tickers to watch and sizes them to your capital. First trading day free.',
    cta: 'Open the app',
    risk: 'Signals are generated by a simulated bot for reference only — not investment advice. Trading carries risk.',
  },
  ja: {
    title: 'AI4Trade Signals · モバイル',
    desc: '取引日ごとに、ボットが注目銘柄を数点選び、あなたの資金に合わせて配分します。初日は無料。',
    cta: 'アプリを開く',
    risk: 'シグナルはシミュレーションボットによる参考情報で、投資助言ではありません。取引にはリスクがあります。',
  },
  de: {
    title: 'AI4Trade Signals · Mobil',
    desc: 'Vor jedem Handelstag wählt der Bot einige Titel aus und passt sie an dein Kapital an. Erster Handelstag gratis.',
    cta: 'App öffnen',
    risk: 'Signale stammen von einem simulierten Bot, nur zur Information — keine Anlageberatung. Handel birgt Risiken.',
  },
};

export function PwaPromo() {
  if (!PWA_URL) return null;
  const locale = useLocale();
  const t = COPY[locale] ?? COPY.en;

  return (
    <div className="mt-8 rounded-lg border border-border bg-muted/30 p-4">
      <div className="flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-center">
        <div>
          <p className="text-sm font-semibold text-foreground">📈 {t.title}</p>
          <p className="mt-1 max-w-2xl text-xs leading-relaxed text-muted-foreground">{t.desc}</p>
        </div>
        <a
          href={PWA_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="shrink-0 rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground hover:opacity-90"
        >
          {t.cta}
        </a>
      </div>
      <p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">{t.risk}</p>
    </div>
  );
}
